name: Preproduction Deployment #shoutout to the exercises session

on:
  push:
    branches:
      - develop
  workflow_dispatch:

# The following secrets are required from the repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER = root
# SSH_KEY_PRE
# SSH_HOST_PRE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push csharptwit-preproduction
        uses: docker/build-push-action@v2
        with:
          context: ./csharp-minitwit
          file: ./csharp-minitwit/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/csharptwit-preproduction:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/csharptwit-preproduction:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/csharptwit-preproduction:webbuildcache,mode=max
          build-args: ENVIRONMENT=Preproduction

      #TODO: Add / adjust tests from py api maybe?

      # - name: Test minitwit
      #   run: |
      #     docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
      #     yes 2>/dev/null | docker-compose up -d
      #     docker run --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging_key
          chmod 600 ~/.ssh/staging_key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_PRE }}

      - name: Copy files to server
        # Updating all files on remote server from the remote_files_preproduction
        run: >
          scp -i ~/.ssh/staging_key -o StrictHostKeyChecking=no
          ./csharp-minitwit/remote_files_preproduction/* $SSH_USER@$SSH_HOST:/csharp-minitwit
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST_PRE }}

      - name: Deploy to server
        # Calls deploy.sh to pull csharp-minitwit image from Docker Hub and spin container up.
        run: |
          ssh -i ~/.ssh/staging_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            export ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTIONSTRING_STAGING }}
            cd /csharp-minitwit
            printenv
            docker compose -f docker-compose.yml pull
            
            # Check if Docker Swarm is initialized, initialize if not
            if ! docker node ls > /dev/null 2>&1; then
              echo "Initializing Docker Swarm..."
              docker swarm init
            else
              echo "Docker Swarm is already initialized."
            fi

            # Check if the stack is already deployed
            if docker stack ls | grep -q minitwit; then
              echo "Removing existing stack 'minitwit'..."
              docker stack rm minitwit
              # Wait a few seconds to ensure the stack is fully removed
              sleep 10
            fi

            # Deploy the stack
            echo "Deploying stack 'minitwit'..."
            docker stack deploy -c docker-compose.yml minitwit
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST_PRE }}
