name: Format check on push
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    # branches:
    #   - feature/software-quality-tools
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./csharp-minitwit/csharp-minitwit.sln

      - name: Format
        run: dotnet format ./csharp-minitwit/csharp-minitwit.sln --verbosity diagnostic

      - name: Push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Automated formatting"
          git push

      - name: Lint C# code
        run: dotnet build